### PR TITLE
fixes https://bugs.launchpad.net/jio/+bug/1467502

### PR DESCRIPTION
**Pull request by punituee**
takes care of truncated files on local machine

### CODE REVIEW

**Comment by sorenh** [comment]
Please submit this upstream. They're much better equipped to review it.

**Comment by punituee** [comment]
this code is present on upstream.

**Comment by rickysarraf** [comment]
On Thursday 09 July 2015 01:17 PM, Puneet Goyal wrote:
>
> this code is present on upstream.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/python-glanceclient/pull/1#issuecomment-119859655>.
>

So, do we want the repository rebased to latest upstream changes, or
just apply this one patch ?

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by punituee** [comment]
I recommend rebasing.

**Comment by rickysarraf** [comment]
That'll also pull in new dependencies. I know Soren was holding it off to
the IceHouse release for a while. Please let's wait for Soren to confirm
first.

On Thu, Jul 9, 2015 at 1:53 PM, Puneet Goyal <notifications@github.com>
wrote:

> I recommend rebasing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/python-glanceclient/pull/1#issuecomment-119871601>
> .
>



-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by punituee** [comment]
No worries. What happens when we rebase after merging some of the code that is already present on upstream?

**Comment by rickysarraf** [comment]
Well.... IF you rebase to the latest, you do pull in your fix, but also
pull in all other changes up till that revision.

On Thu, Jul 9, 2015 at 2:03 PM, Puneet Goyal <notifications@github.com>
wrote:

> No worries. What happens when we rebase after merging some of the code
> that is already present on upstream?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/python-glanceclient/pull/1#issuecomment-119873960>
> .
>



-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by punituee** [comment]
I know that, what I wanted to ask was, what if we merge this PR and at a later moment of time we decide to rebase...will it merge automatically? or there will be a conflict due to existing code?

**Comment by sorenh** [comment]
Which new dependencies will be introduced by rebasing glanceclient?

**Comment by sorenh** [comment]
If we end up not rebasing and this already exists upstream, please submit the cherry-pick. Don't copy/paste code like this.

**Comment by rickysarraf** [comment]
Depends. If it is already in the upstream repo and you cherry-pick, it
should merge/rebase fine. Otherwise, you may get conflicts.

On Thu, Jul 9, 2015 at 2:25 PM, Puneet Goyal <notifications@github.com>
wrote:

> I know that, what I wanted to ask was, what if we merge this PR and at a
> later moment of time we decide to rebase...will it merge automatically? or
> there will be a conflict due to existing code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/python-glanceclient/pull/1#issuecomment-119879754>
> .
>



-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
I was referring to usual bump in versioned dependencies, in requirements.txt

On Thu, Jul 9, 2015 at 2:27 PM, Soren Hansen <notifications@github.com>
wrote:

> Which new dependencies will be introduced by rebasing glanceclient?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/python-glanceclient/pull/1#issuecomment-119880080>
> .
>



-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by punituee** [comment]
I fixed this first and later realized this exists upstream. How do I get the cherry pick commit where this change was made? does git support reverse code change mapping against the commit id's.

Let me check the dependencies change in requirements.txt.

**Comment by sorenh** [comment]
@rickysarraf Yes, but what are they?

**Comment by sorenh** [comment]
@punituee "git reset --hard HEAD^; git cherry-pick commit_id_of_upstream_commit ; git push -f name_of_remote name_of_branch"

git reset --hard HEAD^    <---- Basically removes the topmost commit (the one you added).

**Comment by rickysarraf** [comment]
@sorenh For glanceclient, nothing has been bumped. The requirements.txt was last touched 9 months ago.

**Comment by sorenh** [comment]
Great. Just rebase then.

**Comment by punituee** [comment]
Soren, thanks. I think you misread what I wrote. I really don't have the commit id. Is there a way to figure out in what commit the code change was pushed without going through the history manually?

And yes we should re-base.

**Comment by sorenh** [comment]
@punituee "git blame filename.py" shows the origin of every line in the file.

**Comment by punituee** [comment]
@sorenh thanks again. It shows the latest commit, which has overwritten the previous one. Latest one can not be cherry picked because it edits the code due to other commits in between.
Oh lets just rebase it. If it breaks we can catch it in the gate and revert back to current version and merge just the fix. 
Hope it doesn't come to that.

**Comment by rickysarraf** [comment]
@punituee The repo is rebased now to the latest, i.e. June 30th, 2015. The fix you've proposed is now already pulled in. Please verify and then you may close this PR.

**Comment by punituee** [comment]
Yes it is present. Lets test this further in build.

**Comment by bodepd** [comment]
@rickysarraf why would you rebase an entire repo without testing it? It broke the build environment. We need to reset it back to the previous commit.

**Comment by punituee** [comment]
I had to go through the code manually but I found the commit id for my change upstream
https://github.com/openstack/python-glanceclient/commit/e3600ad7beb7cb4a067038d750e530a64fd1e93a
Since the build environment broke because we rebased, this single commit can be cherry picked.

**Pull request closed without merging**
